一覧表示機能作成 : 1-4. DBと連携
nzzzz27/scala-play_todo-app pull request #3
Opened 2020-08-17 10:17 UTC by nzzzz27

## 必須要件: 1. 一覧表示機能作成: 1-4. DBと連携 
### 行うこと
1-4-1. モデルを定義

2020-08-17 10:25 UTC, korezonzi commented on app/lib/model/Todos.scala
> +
categoryIdは、 `Category.scala`  にて定義してあげましょう！

2020-08-17 10:28 UTC, korezonzi commented on app/lib/model/Todos.scala
> +
Todoにおいては、どのようなステータスが適切か(あると使いやすいか)、考えてみて良いかもですねー。

2020-08-18 05:03 UTC, nzzzz27 commented on app/lib/model/Todos.scala
> +
以下のコミットで修正しました！

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/7ed6010aaf71c9e36e17fcfb532c4a59273cdabc [update] LM: モデルを定義

2020-08-18 05:04 UTC, nzzzz27 commented on app/lib/model/Todos.scala
> +
アドバイスありがとうございます！
この部分を今後どのように使用するのかイメージがついておりませんので、作業を後回しにしています...

2020-08-18 05:21 UTC, korezonzi commented on .bloop/bloop.settings.json
> +}
gitignoreに追加しておきましょう。
他の  `.bloop`  含めて。

2020-08-18 05:22 UTC, korezonzi commented on app/lib/model/Category.scala
> +
Category はStatus のEnumStatus不要ですね。
ただ、他のパラメータは定義すると良いかと思うので、考えてみてくださいー

2020-08-18 05:23 UTC, korezonzi commented on app/lib/model/Todos.scala
> +  id:            Option[Todo.Id],
`Option[Id]` で大丈夫です

2020-08-18 05:30 UTC, korezonzi commented on app/lib/persistence/db/Todo.scala
> +    import Category._
このimport不要かもです。
7,8行目で定義してるので。

2020-08-18 05:33 UTC, korezonzi commented on project/metals.sbt
> +addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.3")
これもgitignoreですかね。
projectフォルダごと。

2020-08-18 05:47 UTC, korezonzi commented on app/lib/model/Todos.scala
> +
OKです。
//TODOなどとして、コメントでその旨記入しておいてくださいー

2020-08-18 07:15 UTC, nzzzz27 commented on .bloop/bloop.settings.json
> +}
以下のコミットで、修正しました。

- .gitignoreの追記
- ファイル削除

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/6d682d2b2946e6f76711ef74ab899b72aeed2dc0 [update] *.bloop/, project/ 追記
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/dd1988d9969abc09fbb4d50be23c666170394cd4　[delete] .bloop/*

2020-08-18 07:16 UTC, nzzzz27 commented on project/metals.sbt
> +addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.3")
以下のコミットで、修正しました。

- .gitignoreの追記
- ファイル削除

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/6d682d2b2946e6f76711ef74ab899b72aeed2dc0 [update] *.bloop/, project/ 追記

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/dd1988d9969abc09fbb4d50be23c666170394cd4  [delete] .bloop/*

2020-08-18 07:23 UTC, nzzzz27 commented on app/lib/model/Todos.scala
> +  id:            Option[Todo.Id],
コメントありがとうございます。

いただいたコードで記載すると、以下のエラーが出てしまい、`Option[Todo.Id]`としています。
このエラーは、どこかの書き方に誤りがあるために起きているのでしょうか？
```
reference to Id is ambiguous;
it is imported twice in the same scope by
import Category._
and import Todo._
```

2020-08-18 07:26 UTC, nzzzz27 commented on app/lib/model/Category.scala
> +
コメントありがとうございます！

実装後回しにします。コメント追記しました。
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/47e4d21edcad965c6c174cdf4545bc8fdd2e92e9 [update] PR指摘点修正 - TODOアノテーション追加

2020-08-18 07:27 UTC, nzzzz27 commented on app/lib/model/Todos.scala
> +
承知しました。コメント追記しました。
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/47e4d21edcad965c6c174cdf4545bc8fdd2e92e9 [update] PR指摘点修正 - TODOアノテーション追加

2020-08-18 07:27 UTC, nzzzz27 commented on app/lib/persistence/db/Todo.scala
> +    import Category._
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/81d3e7259c4913253b7e31fdeed93d2af179d63a [update] PR指摘点修正

2020-08-18 08:51 UTC, korezonzi commented on app/lib/model/Todos.scala
> +  id:            Option[Todo.Id],
済

2020-08-18 10:43 UTC, nzzzz27 commented on app/lib/model/Todos.scala
> +  id:            Option[Todo.Id],
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/96dda0df40f77dcefc64c9bbd24af023264100cb [update] PR指摘点修正

2020-08-19 01:51 UTC, korezonzi reviewed
comment

2020-08-19 01:51 UTC, korezonzi commented on project/metals.sbt
> +addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.3")
ここgitignoreできてないですね。
これ、一度コミットしてしまったら、キャッシュが残ってしまうので、おそらくそれが原因かもですー

以下、試してみてくださいmm
https://qiita.com/fuwamaki/items/3ed021163e50beab7154

2020-08-19 01:51 UTC, korezonzi commented on app/lib/persistence/db/User.scala
> +}
こんな所も

2020-08-19 01:51 UTC, korezonzi commented on app/lib/model/User.scala
> +}
今回、修正するほどでもないですが、
PRには、不要な(意図していない)改行や、 修正は含めないように意識しましょう！

2020-08-19 03:12 UTC, nzzzz27 commented on app/lib/model/User.scala
> +}
すみません、気をつけます！

> PRには、不要な(意図していない)改行や、 修正は含めないように意識しましょう！

こちらを確認・修正するタイミングは、以下で合っていますか？

確認：pushのあと、files changedのタブで確認
修正：ローカルでコードを直して、再度commit push

2020-08-19 07:45 UTC, korezonzi commented on app/lib/model/User.scala
> +}
確認は、コミットする際に diffなどで変更箇所確認後push + PR作成(共有)の際にさらりと確認ですかね。

> 修正：ローカルでコードを直して、再度commit push

その通りです。

2020-08-19 07:52 UTC, korezonzi commented on app/lib/persistence/package.scala
> +    object CategoryRepository extends CategoryRepository
インデント

2020-08-19 08:14 UTC, korezonzi commented on app/lib/model/Category.scala
> +  type EmbeddedId = Entity.EmbeddedId[Id, Category]
ここも `[Id, Category]` が揃うようにインデント 整えましょう。

2020-08-19 08:14 UTC, korezonzi commented on app/lib/model/Todos.scala
> +  type EmbeddedId = Entity.EmbeddedId[Id, Todo]
同様

2020-08-19 08:22 UTC, nzzzz27 commented on app/lib/model/User.scala
> +}
承知しました！ありがとうございます！

2020-08-19 08:33 UTC, nzzzz27 commented on app/lib/model/Todos.scala
> +  type EmbeddedId = Entity.EmbeddedId[Id, Todo]
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/e5b521ef8c677554bfd4e0043f48946cfe593449 [clear] PR指摘分修正 - インデント

2020-08-19 08:33 UTC, nzzzz27 commented on app/lib/model/Category.scala
> +  type EmbeddedId = Entity.EmbeddedId[Id, Category]
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/e5b521ef8c677554bfd4e0043f48946cfe593449 [clear] PR指摘分修正 - インデント

2020-08-19 08:33 UTC, nzzzz27 commented on app/lib/persistence/db/SlickResourceProvider.scala
> +  object CategoryTable extends CategoryTable
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/e5b521ef8c677554bfd4e0043f48946cfe593449 [clear] PR指摘分修正 - インデント

2020-08-19 08:33 UTC, nzzzz27 commented on app/lib/persistence/package.scala
> +    object CategoryRepository extends CategoryRepository
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/e5b521ef8c677554bfd4e0043f48946cfe593449 [clear] PR指摘分修正 - インデント

2020-08-19 08:44 UTC, korezonzi commented on app/model/todos/FormattedTodos.scala
> +  id:            Option[Long],
id: Todo.Id 型の方が良いですかね。

2020-08-19 09:21 UTC, nzzzz27 commented on project/metals.sbt
> +addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.3")
リンクまで、ご丁寧にありがとうございます！
以下のコミットで削除しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/1bad516f3e6d1c66f810042008f954e157b01337 [updae] キャッシュ削除

2020-08-19 10:50 UTC, nzzzz27 commented on app/model/todos/FormattedTodos.scala
> +  id:            Option[Long],
ありがとうございます。以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/c735ef9012eb7102633d82901d06f19f09afa062 LM: モデルを定義 - 型修正

2020-08-20 01:07 UTC, korezonzi commented on app/lib/persistence/db/Category.scala
> +// UserTable: Userテーブルへのマッピングを行う
コピペミスですかね。

2020-08-20 08:36 UTC, nzzzz27 commented on app/lib/persistence/db/Category.scala
> +// UserTable: Userテーブルへのマッピングを行う
です...。以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/99271f3b05bc709bd3c7993c20f27674679ad527 [clear] PR指摘点修正 - 不要なコメントアウト 削除

2020-08-20 09:23 UTC, korezonzi requested changes
Controller、見てる最中ですが、他の箇所

2020-08-20 09:23 UTC, korezonzi commented on app/controllers/todos/TodoController.scala
>      val formattedTodosSeq: Seq[FormattedTodos] = Await.result(formattedTodosSeqFuture, Duration.Inf)
Await.result 不要な気がしますし、使うべきではないかと。

ここ無くして試してもらって良いですか。

2020-08-20 09:23 UTC, korezonzi commented on app/controllers/todos/TodoController.scala
> +      categoryEntitySeq <- onMySQL.CategoryRepository.getAll()
onMySQLは不要かと。importも含め。

2020-08-20 10:16 UTC, nzzzz27 commented on app/controllers/todos/TodoController.scala
> +      categoryEntitySeq <- onMySQL.CategoryRepository.getAll()
アドバイスありがとうござます。
以下の形に直すということで合っていますか？
こうすると、`not found: value TodoRepository`とエラーが出るため、提出した形にしました。

```
// import lib.persistence.`package`.onMySQL

val formattedTodosSeqFuture: Future[Seq[FormattedTodos]]  = for {
   todoEntitySeq     <- TodoRepository.getAll()
   categoryEntitySeq <- CategoryRepository.getAll()
} yield {
```

2020-08-20 10:21 UTC, nzzzz27 commented on app/lib/persistence/Todos.scala
> +}
他の不要コードを含め、削除しました。
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/8cf4c9fbbb557dfde8f9af4601f9d0e94d547086 [clean] 不要なコメントとコードを削除

2020-08-20 10:21 UTC, nzzzz27 commented on app/lib/persistence/Category.scala
> +    }
他の不要コードを含め、削除しました。
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/8cf4c9fbbb557dfde8f9af4601f9d0e94d547086 [clean] 不要なコメントとコードを削除

2020-08-20 10:35 UTC, korezonzi commented on app/controllers/todos/TodoController.scala
> +      categoryEntitySeq <- onMySQL.CategoryRepository.getAll()
合ってます！
not found になるのは、単にimport がないからですかね。

2020-08-20 11:14 UTC, korezonzi reviewed
コメントしましたmm

2020-08-20 11:14 UTC, korezonzi commented on app/model/todo/Common.scala
> +  todo:     Seq[TodoData],
Commonに当たるのは `app/model/todo/Todo.scala` ですかね。
<- これはあくまでTodoの一覧表示のVVなので。

　それと、todoSeq とかの方が良いですね。

2020-08-20 11:14 UTC, korezonzi commented on app/model/todo/Common.scala
> +  todo:     Seq[TodoData],
それとVVTodoとTodoDataの違いが、名前からだとわからないので、
ViewValueで統一した上で、命名した方が良さそうです。
Ex) ViewValueHogeとViewValueFooみたいに

2020-08-20 11:14 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +        categoryEntitySeq.find(_.id == categoryId).get.v
getは基本使わない方が良いです。
例えば上記だと、カテゴリーが0件の際は、categoryEntitySeqには空のSeqが入っているので、その場合、エラーとなります。

2020-08-21 01:29 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +          todo.id,
ここ、 `todoENtity.id` ですね。
entityのidを取得するのは、idのメソッドがあって、eitity.idとして取得出来ます。
<- todo.id(=todoEntity.v.id) だと、Option[T] になり、この場合、Some(xx) なのは自明なので。

https://github.com/ixias-net/ixias/blob/805925cb9574d1c9c5f243611ba5dddc0705d521/framework/ixias-core/src/main/scala/ixias/model/Entity.scala#L30

2020-08-21 01:31 UTC, korezonzi commented on app/model/todo/Todo.scala
> +  id:            Option[Todo.Id],
id: Todo.Id で良いですね。
データがある際(EmbeddedId)は、idもあることは自明なので。

2020-08-21 01:35 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +    val todoDataSeq: Seq[TodoData] = Await.result(todoDataSeqFuture, Duration.Inf)
これない場合、試してもらって良いですか

2020-08-21 01:49 UTC, nzzzz27 commented on app/model/todo/Common.scala
> +  todo:     Seq[TodoData],
アドバイスありがとうございます。
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/c0a8c18d20e5700d079a2371da4d9a8e31ed0aa4 [clean] PR指摘点修正 - クラス名変更

2020-08-21 04:56 UTC, nzzzz27 commented on app/controllers/todos/TodoController.scala
>      val formattedTodosSeq: Seq[FormattedTodos] = Await.result(formattedTodosSeqFuture, Duration.Inf)
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/ffe90c3d8c07c98fe9e84f451f9d3c01450b5a2e [update] PR指摘点修正 - Await削除

2020-08-21 04:56 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +    val todoDataSeq: Seq[TodoData] = Await.result(todoDataSeqFuture, Duration.Inf)
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/ffe90c3d8c07c98fe9e84f451f9d3c01450b5a2e [update] PR指摘点修正 - Await削除

2020-08-21 05:21 UTC, nzzzz27 commented on app/model/todo/Common.scala
> +  todo:     Seq[TodoData],
以下のコミットで再修正しました。
 https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/38e1f83ade6e84d707a12be161d8a5821e4625c9

2020-08-24 04:53 UTC, nzzzz27 commented on app/model/todo/Todo.scala
> +  id:            Option[Todo.Id],
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/cf0f293c13ee90e6b54b6f0159a9b982c1b854fc [update] PR指摘点修正 - Todo.idの型変更

2020-08-24 04:53 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +          todo.id,
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/cf0f293c13ee90e6b54b6f0159a9b982c1b854fc [update] PR指摘点修正 - Todo.idの型変更

2020-08-24 04:53 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +        categoryEntitySeq.find(_.id == categoryId).get.v
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/56dffde3a48b6fb5729543e11a04f9ee3ddcf7ab [update] PR指摘点修正 - getを使わない
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/c65dc509ea3d5048b8ab2ba7a124bb3ed825aa21 [update] PR指摘点修正 - getを使わない

2020-08-24 05:02 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +      categoryEntitySeq <- onMySQL.CategoryRepository.getAll()
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/82e54af7676f891d9d3f651b91fe8c835d214769 [update] PR指摘点修正 - onMySQL削除

2020-08-24 05:02 UTC, nzzzz27 commented on app/controllers/todos/TodoController.scala
> +      categoryEntitySeq <- onMySQL.CategoryRepository.getAll()
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/82e54af7676f891d9d3f651b91fe8c835d214769 [update] PR指摘点修正 - onMySQL削除

2020-08-24 05:53 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +        val categoryId: Option[Category.Id] = categoryEntitySeq.find(_.id == todo.category_id).map (i => i.id)
`map(i => i.id)` のiが何か分かりづらいので、  `ca => ca.id` や `map(_.id)`  などの方が直感的ですかね。

2020-08-24 07:30 UTC, korezonzi commented on conf/routes
> +GET    /todo                        controllers.todos.TodoController.showList
詳細なども作ることを考えると、`todo/all`  など、todoの中でも役割を詳細にしましょう。

2020-08-24 07:34 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +import lib.persistence.`package`.onMySQL._
不要なimportは削除しましょう。

2020-08-24 07:35 UTC, korezonzi reviewed
細かい箇所のコメントです。

2020-08-24 07:35 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +import scala.util.{Success, Failure, Try}
ここも使っていないなら、削除

2020-08-24 08:33 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +import scala.util.{Success, Failure, Try}
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/99c0ef2e5dcf85bf256d54f63fd4d3c371ad7ba7  [clear] PR指摘点修正 - 不要import削除/value名変更

2020-08-24 08:33 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +import lib.persistence.`package`.onMySQL._
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/99c0ef2e5dcf85bf256d54f63fd4d3c371ad7ba7  [clear] PR指摘点修正 - 不要import削除/value名変更

2020-08-24 08:34 UTC, nzzzz27 commented on conf/routes
> +GET    /todo                        controllers.todos.TodoController.showList
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/2f4da9e3323ef2bb811dbfa45f078d359df74aba　[update] PR指摘点修正 - routing修正, ホームディレクトリアクセス時リダイレクト処理

2020-08-24 08:34 UTC, nzzzz27 commented on app/controllers/todo/TodoController.scala
> +        val categoryId: Option[Category.Id] = categoryEntitySeq.find(_.id == todo.category_id).map (i => i.id)
以下のコミットで修正しました。

https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/99c0ef2e5dcf85bf256d54f63fd4d3c371ad7ba7  [clear] PR指摘点修正 - 不要import削除/value名変更

2020-08-24 08:47 UTC, korezonzi commented on app/controllers/Home.scala
> +    Redirect(todo.routes.TodoController.showList())
ここはOk(~~)ですかね。
理由として、Okが200番のステータスコード(成功)を意味するものなので。

https://developer.mozilla.org/ja/docs/Web/HTTP/Status

2020-08-24 08:51 UTC, korezonzi commented on app/controllers/Home.scala
> +    Redirect(todo.routes.TodoController.showList())
@nzzzz27 さん
あ、そもそも、ここは修正いらないと思います。

修正の必要があるのは、この呼び出し先の `views.html.Home` なので

2020-08-24 09:32 UTC, nzzzz27 commented on app/controllers/Home.scala
> +    Redirect(todo.routes.TodoController.showList())
以下のコミットで修正しました。
 
https://github.com/nzzzz27/scala-play_todo-app/pull/3/commits/2f4da9e3323ef2bb811dbfa45f078d359df74aba [update] PR指摘点修正 - routing修正, ホームディレクトリアクセス時リダイレクト処理

2020-08-24 09:51 UTC, korezonzi reviewed
コメントしました。

2020-08-24 09:51 UTC, korezonzi commented on app/controllers/Home.scala
> +import java.lang.ProcessBuilder.Redirect
不要なimport...

2020-08-24 09:51 UTC, korezonzi commented on app/controllers/Home.scala
> +     val vv = ViewValueHome(
インデント ずれてますね。。(字下げが3文字になってます)

2020-08-24 09:51 UTC, korezonzi commented on app/controllers/Home.scala
> +
この改行、不要ですね

2020-08-24 09:51 UTC, korezonzi commented on app/controllers/todo/TodoController.scala
> +import lib.persistence.`package`.onMySQL._
onMySQLも不要だと思います。

2020-08-24 09:51 UTC, korezonzi commented on app/views/Home.scala.html
> +    <li><a href="/todo/list">Todo一覧</a></li>
Play のhref の書き方です。
基本はコントローラーのアクションを呼ぶことが多いです。

https://www.playframework.com/documentation/ja/1.2.x/tags
https://ameblo.jp/h-ogawa1216/entry-11396496626.html

2020-08-25 05:15 UTC, korezonzi approved these changes
OKです！
マージしましょう。

2020-08-25 05:37 UTC, merged